#! /usr/bin/env python

from hotspotCall.run import *
import argparse

parser = argparse.ArgumentParser(prog = "hotspotCall")

parser.add_argument("--version", action = "version", version = "hotspotCall-0.1.0")

parser.add_argument("targetBamPath", metavar = "target.bam", type = str,
                          help = "the path to the target bam file")

parser.add_argument("controlBamPath", metavar = "control.bam", type = str,
                          help = "the path to the control bam file")

parser.add_argument("outputPath", metavar = "output_file_prefix", type = str,
                          help = "the path to the output_file_prefix")

parser.add_argument("hotspotList", metavar = "mutations.bed", type = str,
                         help = "the bed format file that lists mutations")

parser.add_argument('-f', choices=['vcf', 'anno'], default = 'anno',
                    help = "the format of output file vcf or annovar (tsv) format")

parser.add_argument('-q', metavar = "mapping_qual_thres", default='20', type=int,
                    help = "threshold for mapping quality for calculating base counts")

parser.add_argument('-Q', metavar = "base_qual_thres", default='15', type=int,
                    help = "threshold for base quality for calculating base counts")

parser.add_argument('-m', metavar = "min_allele_freq", default = 0.01, type = float)

args = parser.parse_args()

main(args)

