#! /usr/bin/env python

from hotspotCall.run import *
import argparse

parser = argparse.ArgumentParser(prog = "hotspotCall")

parser.add_argument("--version", action = "version", version = "hotspotCall-0.1.0")
parser.add_argument("tumor_bam", metavar = "tumor.bam", type = str, help = "the path to the tumor bam file")
parser.add_argument("control_bam", metavar = "control.bam", type = str, help = "the path to the control bam file")
parser.add_argument("output_file", metavar = "output_file", type = str, help = "the path to the output file")
parser.add_argument("hotspot_file", metavar = "hotspot_mutations.bed", type = str, help = "the bed format file that lists mutations")
parser.add_argument('-S', metavar = 'samtools_params', type = str, default = "-B -q 20 -Q2 -d 10000000")
parser.add_argument('-t', metavar = "min_tumor_misrate", default = 0.05, type = float)
parser.add_argument('-c', metavar = "max_control_misrate", default = 0.1, type = float)
parser.add_argument('-R', metavar = "T/N ratio_control", default = 0.1, type = float)
parser.add_argument('-m', metavar = "min_lod_score", default = 8.0, type = float)
parser.add_argument('-r', metavar = "rna.bam" , type = str, help = "the path to the RNA bam file")
args = parser.parse_args()

main(args)

